import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export async function initCommand() {
  console.log(chalk.cyan.bold('\n  Skopix Setup\n'));
  console.log(chalk.dim('  This will create a .skopix.env file in your current directory.\n'));

  const answers = await inquirer.prompt([
    {
      type: 'list',
      name: 'provider',
      message: 'Which LLM provider would you like to use?',
      choices: [
        { name: 'Google Gemini (free tier available)', value: 'gemini' },
        { name: 'Ollama (local, completely free)', value: 'ollama' },
        { name: 'OpenAI GPT-4 Vision', value: 'openai' },
      ],
    },
    {
      type: 'input',
      name: 'geminiKey',
      message: 'Enter your Gemini API key:',
      when: (a) => a.provider === 'gemini',
      validate: (v) => v.trim().length > 0 || 'API key is required',
    },
    {
      type: 'input',
      name: 'ollamaUrl',
      message: 'Ollama base URL:',
      default: 'http://localhost:11434',
      when: (a) => a.provider === 'ollama',
    },
    {
      type: 'input',
      name: 'ollamaModel',
      message: 'Ollama model name (must support vision or text):',
      default: 'llama3.1',
      when: (a) => a.provider === 'ollama',
    },
    {
      type: 'input',
      name: 'openaiKey',
      message: 'Enter your OpenAI API key:',
      when: (a) => a.provider === 'openai',
      validate: (v) => v.trim().length > 0 || 'API key is required',
    },
    {
      type: 'confirm',
      name: 'setupJira',
      message: 'Would you like to set up Jira integration?',
      default: false,
    },
    {
      type: 'input',
      name: 'jiraUrl',
      message: 'Jira base URL (e.g. https://yourorg.atlassian.net):',
      when: (a) => a.setupJira,
    },
    {
      type: 'input',
      name: 'jiraEmail',
      message: 'Jira account email:',
      when: (a) => a.setupJira,
    },
    {
      type: 'password',
      name: 'jiraToken',
      message: 'Jira API token (https://id.atlassian.com/manage-profile/security/api-tokens):',
      when: (a) => a.setupJira,
    },
    {
      type: 'input',
      name: 'jiraProject',
      message: 'Jira project key (e.g. QA, BUG):',
      when: (a) => a.setupJira,
    },
    {
      type: 'confirm',
      name: 'setupLinear',
      message: 'Would you like to set up Linear integration?',
      default: false,
    },
    {
      type: 'password',
      name: 'linearKey',
      message: 'Linear API key:',
      when: (a) => a.setupLinear,
    },
    {
      type: 'input',
      name: 'linearTeam',
      message: 'Linear team ID:',
      when: (a) => a.setupLinear,
    },
    {
      type: 'confirm',
      name: 'setupGithub',
      message: 'Would you like to set up GitHub Issues integration?',
      default: false,
    },
    {
      type: 'input',
      name: 'githubRepo',
      message: 'GitHub repo (e.g. owner/repo):',
      when: (a) => a.setupGithub,
    },
    {
      type: 'password',
      name: 'githubToken',
      message: 'GitHub personal access token:',
      when: (a) => a.setupGithub,
    },
  ]);

  // Build env file content
  const lines = [
    '# Skopix Configuration',
    '# Generated by skopix init',
    '',
    `SKOPIX_PROVIDER=${answers.provider}`,
    '',
  ];

  if (answers.provider === 'gemini') {
    lines.push(`GEMINI_API_KEY=${answers.geminiKey}`);
  } else if (answers.provider === 'ollama') {
    lines.push(`OLLAMA_BASE_URL=${answers.ollamaUrl}`);
    lines.push(`OLLAMA_MODEL=${answers.ollamaModel}`);
  } else if (answers.provider === 'openai') {
    lines.push(`OPENAI_API_KEY=${answers.openaiKey}`);
  }

  if (answers.setupJira) {
    lines.push('', '# Jira');
    lines.push(`JIRA_BASE_URL=${answers.jiraUrl}`);
    lines.push(`JIRA_EMAIL=${answers.jiraEmail}`);
    lines.push(`JIRA_API_TOKEN=${answers.jiraToken}`);
    lines.push(`JIRA_PROJECT_KEY=${answers.jiraProject}`);
  }

  if (answers.setupLinear) {
    lines.push('', '# Linear');
    lines.push(`LINEAR_API_KEY=${answers.linearKey}`);
    lines.push(`LINEAR_TEAM_ID=${answers.linearTeam}`);
  }

  if (answers.setupGithub) {
    lines.push('', '# GitHub');
    lines.push(`GITHUB_REPO=${answers.githubRepo}`);
    lines.push(`GITHUB_TOKEN=${answers.githubToken}`);
  }

  const envPath = path.resolve(process.cwd(), '.skopix.env');
  await fs.writeFile(envPath, lines.join('\n') + '\n');

  // Also create a sample credentials file
  const credsSample = [
    '# Skopix credentials file',
    '# Use with: skopix run --credentials credentials.yaml',
    '# Values are passed to the AI agent for form filling',
    '',
    'credentials:',
    '  - label: "Main test account"',
    '    fields:',
    '      email: "testuser@example.com"',
    '      password: "yourpassword"',
    '      username: "testuser"',
    '',
    '  - label: "Admin account"',
    '    fields:',
    '      email: "admin@example.com"',
    '      password: "adminpassword"',
  ].join('\n');

  const credsPath = path.resolve(process.cwd(), 'credentials.yaml');
  if (!await fs.pathExists(credsPath)) {
    await fs.writeFile(credsPath, credsSample);
    console.log(chalk.dim(`\n  Sample credentials file created → credentials.yaml`));
  }

  console.log(chalk.green.bold('\n  ✓ Configuration saved → .skopix.env'));
  console.log(chalk.dim('\n  Add .skopix.env to your .gitignore to keep secrets safe!\n'));
  console.log(chalk.white('  You\'re ready to go. Try:'));
  console.log(chalk.cyan('  skopix run --url https://yoursite.com --goal "test the login flow"\n'));
}
